<?php
   $mac=$datos['mac'];
   $ip=$datos['ip'];
   $username=$datos['username'];
   $linklogin=$datos['link-login'];
   $linkorig=$datos['link-orig'];
   $error=$datos['error'];
   $chapid=$datos['chap-id'];
   $chapchallenge=$datos['chap-challenge'];
   $linkloginonly=$datos['link-login-only'];
   $linkorigesc=$datos['link-orig-esc'];
   $macesc=$datos['mac-esc'];
?>